// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxMessage struct {
	ID           uuid.UUID        `json:"id"`
	Topic        string           `json:"topic"`
	Headers      *json.RawMessage `json:"headers"`
	Payload      json.RawMessage  `json:"payload"`
	PartitionKey *string          `json:"partition_key"`
	CreatedAt    time.Time        `json:"created_at"`
	ProcessedAt  *time.Time       `json:"processed_at"`
	Error        *string          `json:"error"`
}

type Product struct {
	ID            uuid.UUID      `json:"id"`
	Name          string         `json:"name"`
	Sku           string         `json:"sku"`
	Price         pgtype.Numeric `json:"price"`
	StockQuantity int32          `json:"stock_quantity"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}
