// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const productCreate = `-- name: ProductCreate :exec
INSERT INTO products (
	id,
	name,
	sku,
	price,
	stock_quantity,
	created_at,
	updated_at
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7
)
`

type ProductCreateParams struct {
	ID            uuid.UUID      `json:"id"`
	Name          string         `json:"name"`
	Sku           string         `json:"sku"`
	Price         pgtype.Numeric `json:"price"`
	StockQuantity int32          `json:"stock_quantity"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

func (q *Queries) ProductCreate(ctx context.Context, db DBTX, arg ProductCreateParams) error {
	_, err := db.Exec(ctx, productCreate,
		arg.ID,
		arg.Name,
		arg.Sku,
		arg.Price,
		arg.StockQuantity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const productListAll = `-- name: ProductListAll :many
SELECT id, name, sku, price, stock_quantity, created_at, updated_at FROM products
`

func (q *Queries) ProductListAll(ctx context.Context, db DBTX) ([]Product, error) {
	rows, err := db.Query(ctx, productListAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Price,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
